language: node_js

node_js:
- "6.9.5"

services:
- mongodb

after_success:
  - node ./node_modules/istanbul/index.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && node ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info
