language: node_js

node_js:
- "6.9.5"

services:
- mongodb

after_success:
  - node ./node_modules/istanbul/index.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
